// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8cC8o4ptfP3MwUBbbTvdeuFc6K1W9dAE',
    appId: '1:256836786879:web:486b39224d6e168bf1840a',
    messagingSenderId: '256836786879',
    projectId: 'flutter-fastlane-937a0',
    authDomain: 'flutter-fastlane-937a0.firebaseapp.com',
    storageBucket: 'flutter-fastlane-937a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaL-MJCrtfNAW4hTVlUe_CedfPJNE56wo',
    appId: '1:256836786879:android:b503d2da9a33417ff1840a',
    messagingSenderId: '256836786879',
    projectId: 'flutter-fastlane-937a0',
    storageBucket: 'flutter-fastlane-937a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkqdwa4StLHAqvb_jceSKkurGhcuPbOU',
    appId: '1:256836786879:ios:e93103d85c359a73f1840a',
    messagingSenderId: '256836786879',
    projectId: 'flutter-fastlane-937a0',
    storageBucket: 'flutter-fastlane-937a0.appspot.com',
    iosBundleId: 'com.example.flutterFastlane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkqdwa4StLHAqvb_jceSKkurGhcuPbOU',
    appId: '1:256836786879:ios:e93103d85c359a73f1840a',
    messagingSenderId: '256836786879',
    projectId: 'flutter-fastlane-937a0',
    storageBucket: 'flutter-fastlane-937a0.appspot.com',
    iosBundleId: 'com.example.flutterFastlane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8cC8o4ptfP3MwUBbbTvdeuFc6K1W9dAE',
    appId: '1:256836786879:web:9b060423bdb0b61bf1840a',
    messagingSenderId: '256836786879',
    projectId: 'flutter-fastlane-937a0',
    authDomain: 'flutter-fastlane-937a0.firebaseapp.com',
    storageBucket: 'flutter-fastlane-937a0.appspot.com',
  );
}
