# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Debug the Slack integration"
  lane :slack_debug do
    slack(
          message: "This is a test message from the Fastlane Slack Bot",
          success: true,
          slack_url: ENV["SLACK_URL"]
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Increments version in the pubspec.yaml"
    lane :increment_version do
      # script.rb is a ruby script that increments the build number in pubspec.yaml
      system("ruby ../increase-version-script.rb")
  end

  # uses firebase_app_distribution plugin
  desc "Uses Firebase App Distribution to distribute the APK to testers"
    lane :firebase_distribute do
        sh "flutter build apk -v"
        gradle(
          task: "assemble",
          build_type: "Release"
        )
        # use plugin for distributing the app to beta testers
        release = firebase_app_distribution(
            service_credentials_file: "./fastlane/credentials.json",
            app: ENV["FIREBASE_APP_ID"],
            android_artifact_type: "APK",
            android_artifact_path:"../build/app/outputs/apk/release/app-release.apk",
            testers_file: "./fastlane/tester-list.txt",
            release_notes_file: "./fastlane/release-notes.txt",
            debug: true
        )
        # inform team members
        slack(
          message: "Successfully submitted a new App Update for Beta Testing",
          success: true,
          slack_url: ENV["SLACK_URL"]
        )
    end

    error do |lane, exception|
      slack(
        message: "Something went wrong with the deployment.",
        success: false,
        slack_url: ENV["SLACK_URL"],
        payload: { "Error Info" => exception.error_info.to_s }
      )
    end
end
