name: flutter-fastlane-flow

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
    # Job 1 ->
    CI-Prod:
      name: Apk uploading on Firebase App Distribution
      runs-on: ubuntu-latest
  
      steps:
        # Step 1 Checkout Repository
        - name: Checkout repository
          uses: actions/checkout@v4
  
        # Step 2 Setup JDK
        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: 17
  
        # Step 3 Setup Ruby
        - name: Setup Ruby
          env: 
            BUNDLE_GEMFILE: ${{ github.workspace }}/android/Gemfile
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.3'
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically

        # Step 5 Install the Firebase app distribution plugin with fastlane
        - name: Install Firebase app distribution plugin
          run: bundle exec fastlane add_plugin firebase_app_distribution
          working-directory: ./android
  
        # Step 6 Run the Base64 command to decode our PRIVATE_SERVICE_ACCOUNT_KEY and create the private-decoded-key.json file of our service account
        - name: Generate credentials.json file
          uses: timheuer/base64-to-file@v1.2
          with:
            fileName: 'credentials.json'
            fileDir: './android/fastlane'
            encodedString: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      
        # Step 7 Run the fastlane command to update versionCode and versionName based on latest build uploaded on firebase
        - name: Upgrade build version
          run: bundle exec fastlane increment_version
          working-directory: ./android
  
        # Step 8 Run the fastlane command to upload the build
        - name: Upload Apk to Firebase
          run: bundle exec fastlane firebase_distribute
          working-directory: ./android
          env:
            FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}