name: flutter-fastlane-flow

on:
    push:
      branches: [ fastlane-with-github-action ]
jobs:
    # Job 1 ->
    CI-Prod:
      name: Apk uploading on Firebase App Distribution
      runs-on: ubuntu-latest
  
      steps:
        # Step 1 Checkout Repository
        - name: Checkout repository
          uses: actions/checkout@v2
  
        # Step 2 Setup JDK
        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: 17
  
        # Step 3 Setup Ruby
        - name: Setup Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 'ruby 3.2.3'
  
        # Step 4 Install the bundler & Fastlane (Create environment for ruby to avoid dependency hell and manage the dependencies versions)
        - name: Install bundler
          run: |
            gem install bundler:2.5.13
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
          working-directory: ./android

        # Step 5 Install the Firebase app distribution plugin with fastlane
        - name: Install Firebase app distribution plugin
          run: bundle exec fastlane add_plugin firebase_app_distribution
          working-directory: ./android
  
        # Step 6 Run the Base64 command to decode our PRIVATE_SERVICE_ACCOUNT_KEY and create the private-decoded-key.json file of our service account
        - name: Generate private-decoded-key.json file
          run: echo ${{secrets.SERVICE_ACCOUNT_KEY}} | base64 -d > /fastlane/credentials.json
          working-directory: ./android
            
        # Step 7 Run the fastlane command to update versionCode and versionName based on latest build uploaded on firebase
        - name: Upgrade build version
          run: bundle exec fastlane increment_version
          working-directory: ./android
  
        # Step 8 Run the fastlane command to upload the build
        - name: Upload Apk to Firebase
          run: bundle exec fastlane firebase_distribute
          working-directory: ./android
          env:
            FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}